version: '3.5'
services:
  mysql:
    image: mysql:8.0.32
    container_name: hydrogen_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: 123456
      - MYSQL_DATABASE: hyderogen
    ports:
      - "3306:3306"

  zookeeper:
  image: wurstmeister/zookeeper
  container_name: zookeeper_hydrogen
  restart: always
  ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_biz
    restart: always
    ports:
      - "9092:9092"
      - "1099:1099"

    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # 自动创建 topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_hydrogen:2181
      KAFKA_CREATE_TOPICS: "my-topic"
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
