version: '3.0'
services:
  mysql:
    image: mysql:8.0.32
    container_name: hydrogen_mysql
    restart: always
    # please do not use these settings in product environment
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=hydrogen
    ports:
      - "3306:3306"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_hydrogen
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_hydrogen
    restart: always
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true # auto create topic while not exists
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper_hydrogen:2181
      - KAFKA_CREATE_TOPICS=my-topic
      - KAFKA_LOG_RETENTION_HOURS=24
